[package]
name = "boggler"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6"
clap = { version = "3.0", features = ["derive"] }
crossterm = "0.22"

[build-dependencies]
ureq = "2.4"
regex = "1.5"
flate2 = "1.0"
